const products=[{"productName":"Sole - Fillet","ProductDescription":"Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.","productImage":"https://robohash.org/aspernaturdictaquo.png?size=50x50&set=set1","productPrice":"$9.39"},
    {"productName":"Salmon - Atlantic, Skin On","ProductDescription":"In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.","productImage":"https://robohash.org/nisiesserem.png?size=50x50&set=set1","productPrice":"$5.95"},
    {"productName":"Cheese - Pied De Vents","ProductDescription":"Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.","productImage":"https://robohash.org/etillumculpa.png?size=50x50&set=set1","productPrice":"$8.35"},
    {"productName":"Mustard - Dijon","ProductDescription":"Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.","productImage":"https://robohash.org/istecumqueaut.png?size=50x50&set=set1","productPrice":"$9.32"},
    {"productName":"Hersey Shakes","ProductDescription":"Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.","productImage":"https://robohash.org/autemteneturquos.png?size=50x50&set=set1","productPrice":"$2.83"},
    {"productName":"Chocolate - Milk, Callets","ProductDescription":"Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.","productImage":"https://robohash.org/architectosaepehic.png?size=50x50&set=set1","productPrice":"$8.95"},
    {"productName":"Food Colouring - Pink","ProductDescription":"Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.","productImage":"https://robohash.org/voluptatibusdoloribuspossimus.png?size=50x50&set=set1","productPrice":"$5.87"},
    {"productName":"Anchovy In Oil","ProductDescription":"Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.","productImage":"https://robohash.org/quiacorruptiunde.png?size=50x50&set=set1","productPrice":"$6.85"},
    {"productName":"Alize Gold Passion","ProductDescription":"Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.","productImage":"https://robohash.org/inventorerepellendusquas.png?size=50x50&set=set1","productPrice":"$5.33"},
    {"productName":"Ice Cream - Super Sandwich","ProductDescription":"Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.","productImage":"https://robohash.org/perspiciatissinteaque.png?size=50x50&set=set1","productPrice":"$6.28"}]

    export default products;