const products=[{"productName":"Juice - V8 Splash","ProductDescription":"Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.","productImage":"https://robohash.org/omnisetbeatae.png?size=50x50&set=set1","productPrice":"$0.61","productId":1},
    {"productName":"Bread - Onion Focaccia","ProductDescription":"Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.","productImage":"https://robohash.org/minimanobisrerum.png?size=50x50&set=set1","productPrice":"$7.32","productId":2},
    {"productName":"Bread Fig And Almond","ProductDescription":"Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.","productImage":"https://robohash.org/etiurequasi.png?size=50x50&set=set1","productPrice":"$7.13","productId":3},
    {"productName":"C - Plus, Orange","ProductDescription":"Phasellus in felis. Donec semper sapien a libero. Nam dui.","productImage":"https://robohash.org/ipsamcupiditatedignissimos.png?size=50x50&set=set1","productPrice":"$6.75","productId":4},
    {"productName":"Veal - Brisket, Provimi, Bone - In","ProductDescription":"Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.","productImage":"https://robohash.org/occaecatietquia.png?size=50x50&set=set1","productPrice":"$7.00","productId":5},
    {"productName":"Nut - Pumpkin Seeds","ProductDescription":"Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.","productImage":"https://robohash.org/culpaeteos.png?size=50x50&set=set1","productPrice":"$0.84","productId":6},
    {"productName":"Artichokes - Knobless, White","ProductDescription":"Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.","productImage":"https://robohash.org/uteaquesequi.png?size=50x50&set=set1","productPrice":"$2.01","productId":7},
    {"productName":"Turkey - Breast, Bone - In","ProductDescription":"Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.","productImage":"https://robohash.org/assumendautanimi.png?size=50x50&set=set1","productPrice":"$0.94","productId":8},
    {"productName":"Cake - Cake Sheet Macaroon","ProductDescription":"Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.","productImage":"https://robohash.org/expeditaullamquae.png?size=50x50&set=set1","productPrice":"$4.81","productId":9},
    {"productName":"Crush - Cream Soda","ProductDescription":"Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.","productImage":"https://robohash.org/etnihilmagni.png?size=50x50&set=set1","productPrice":"$4.93","productId":10}]

    export default products;